### ISSUE TITLE
It seems that ScriptableObject would not work if "reload domain" is disabled

### ISSUE THREAD

**Issue by TMPxyz** [kadinche/Kassets#23]
![image](https://github.com/kadinche/Kassets/assets/6214920/df4aaf7d-a43f-4c1f-b9fd-873bcf113c18)

The unity feature "Enter Play mode settings" could greatly improve the speed of entering play mode, but if disable the "reload domain" option, it would cause troubles as the OnEnable/OnDisable would not be called on ScriptableObject when enter play mode.

I wonder if there's workaround for ScriptableObject.

**Comment by TMPxyz** [comment]
Found some references:

- https://docs.unity3d.com/ScriptReference/InitializeOnEnterPlayModeAttribute.html
- https://docs.unity3d.com/Manual/ConfigurableEnterPlayModeDetails.html

**Comment by ripandy** [comment]
Thank you for pointing out both issues and references!

> * https://docs.unity3d.com/Manual/ConfigurableEnterPlayModeDetails.html

A very helpful reference, thank you!

A quick look at the issue, I think the `InitializeOnEnterPlayModeAttribute` looks good enough.
Let me see if it would work.

**Comment by ripandy** [comment]
I found out that `InitializeOnEnterPlayModeAttribute` doesn't work.
I have tried some workaround, and can only hope it works. 🤞
closing with PR #24
